// Design Tokens Configuration for React
// Generated by design-tokens-sync

module.exports = {
  tokens: {
    input: 'tokens.json',
    validation: {
      required: ['core.colors', 'core.spacing', 'core.typography'],
      optional: ['semantic', 'component', 'core.shadows', 'core.borderRadius']
    }
  },
  output: {
    css: 'src/styles/tokens.css',
    typescript: 'src/types/tokens.d.ts',
    tailwind: 'tailwind.config.js'
  },
  react: {
    // React-specific token generation
    hooks: 'src/hooks/useTokens.ts',
    components: 'src/components/tokens/',
    styledComponents: true,
    emotionSupport: false
  },
  git: {
    enabled: true,
    autoCommit: true,
    autoPush: false,
    commitMessage: '🎨 Update design tokens'
  },
  analytics: {
    enabled: true,
    autoCollect: true,
    scanDirs: ['src/**/*'],
    fileExtensions: ['.ts', '.tsx', '.js', '.jsx', '.css', '.scss'],
    outputDir: '.tokens-analytics'
  },
  watch: {
    enabled: true,
    ignore: ['node_modules', '.git', 'dist', 'build', '.next']
  },
  build: {
    // Build integration
    beforeBuild: 'npm run tokens:sync',
    validateBeforeCommit: true
  }
}; 