// Design Tokens Configuration
// Generated by design-tokens-sync

module.exports = {
  "tokens": {
    "input": "tokens.json",
    "validation": {
      "required": [
        "colors"
      ],
      "optional": [
        "spacing",
        "typography",
        "borderRadius"
      ]
    }
  },
  "output": {
    "css": "src/styles/tokens.css",
    "tailwind": "tailwind.config.js",
    "typescript": "src/types/tokens.d.ts"
  },
  "git": {
    "enabled": false,
    "autoCommit": true,
    "autoPush": false,
    "commitMessage": "🎨 Update design tokens"
  },
  "analytics": {
    "enabled": true,
    "autoCollect": true
  },
  "watch": {
    "enabled": true,
    "ignore": [
      "node_modules",
      ".git",
      "dist",
      "build"
    ]
  }
};
